language:
  python
dist:
  trusty
python:
  - 3.6
addons:
  apt:
    packages:
      - python-dev
      - python-pip
      - python3-dev
env:
  global:
    - EML2_1_1_RULES=$TRAVIS_BUILD_DIR/src/metapype/eml2_1_1/rules.json
before_install:
  - sudo apt-get -q update
install:
  - pip install --upgrade pip setuptools
script:
  # Travis clones the project to $TRAVIS_BUILD_DIR and CDs there before running
  # the scripts.
  - ls -lr
  - pip install -r ./requirements.txt
  - pip install -e ./src
  - python --version
  - pip freeze
  - pip check || true
  - pytest
after_success: