language:
  python
dist:
  focal
python:
  - 3.8
addons:
  apt:
    packages:
      - python-dev
      - python3-dev
env:
  global:
    - EML_RULES=$TRAVIS_BUILD_DIR/src/metapype/eml/rules.json
    - TEST_DATA=$TRAVIS_BUILD_DIR/tests/data
before_install:
  - sudo apt-get -q update
install:
  - pip install --upgrade pip setuptools
script:
  # Travis clones the project to $TRAVIS_BUILD_DIR and CDs there before running
  # the scripts.
  - ls -lR
  - pip install -r ./requirements.txt
  - pip install -e .
  - python --version
  - pip freeze
  - pip check || true
  - cp $TRAVIS_BUILD_DIR/src/metapype/config.py.template $TRAVIS_BUILD_DIR/src/metapype/config.py
  - pytest
after_success:
