#!/usr/bin/env python
# -*- coding: utf-8 -*-

""":Mod: names

:Synopsis:

:Author:
    servilla

:Created:
    6/18/18
"""
import daiquiri


logger = daiquiri.getLogger('names: ' + __name__)

# Named constants for EML 2.1.1 metadata element names
ABSTRACT = 'abstract'
ACCESS = 'access'
ACCURACY = 'accuracy'
ADDITIONALINFO = 'additionalInfo'
ADDITIONALMETADATA = 'additionalMetadata'
ADDRESS = 'address'
ADMINISTRATIVEAREA = 'administrativeArea'
ALLOW = 'allow'
ALTERNATEIDENTIFIER = 'alternateIdentifier'
ASSOCIATEDPARTY = 'associatedParty'
ATTRIBUTE = 'attribute'
ATTRIBUTEACCURACYEXPLANATION = 'attributeAccuracyExplanation'
ATTRIBUTEACCURACYREPORT = 'attributeAccuracyReport'
ATTRIBUTEACCURACYVALUE = 'attributeAccuracyValue'
ATTRIBUTEDEFINITION = 'attributeDefinition'
ATTRIBUTELABEL = 'attributeLabel'
ATTRIBUTELIST = 'attributeList'
ATTRIBUTENAME = 'attributeName'
ATTRIBUTEORIENTATION = 'attributeOrientation'
AUTHENTICATION = 'authentication'
BANDGAPBYTES = 'bandgapbytes'
BANDROWBYTES = 'bandrowbytes'
BEGINDATE = 'beginDate'
BINARYRASTERFORMAT = 'binaryRasterFormat'
BOUNDINGCOORDINATES = 'boundingCoordinates'
BOUNDS = 'bounds'
BYTEORDER = 'byteorder'
CALENDARDATE = 'calendarDate'
CASESENSITIVE = 'caseSensitive'
CHARACTERENCODING = 'characterEncoding'
CITATION = 'citation'
CITY = 'city'
CODE = 'code'
CODEDEFINITION = 'codeDefinition'
CODEEXPLANATION = 'codeExplanation'
CODESETNAME = 'codesetName'
CODESETURL = 'codesetURL'
COLLAPSEDELIMITERS = 'collapseDelimiters'
COMMONNAME = 'commonName'
COMPLEX = 'complex'
COMPRESSIONMETHOD = 'compressionMethod'
CONNECTION = 'connection'
CONTACT = 'contact'
COVERAGE = 'coverage'
COUNTRY = 'country'
CREATOR = 'creator'
CUSTOMUNIT = 'customUnit'
DATAFORMAT = 'dataFormat'
DATASET = 'dataset'
DATATABLE = 'dataTable'
DATETIME = 'dateTime'
DEFINITION = 'definition'
DEFINITIONATTRIBUTEREFERENCE = 'definitionAttributeReference'
DELIVERYPOINT = 'deliveryPoint'
DENY = 'deny'
DESCRIBES = 'describes'
DISTRIBUTION = 'distribution'
EASTBOUNDINGCOORDINATE = 'eastBoundingCoordinate'
ELECTRONICMAILADDRESS = 'electronicMailAddress'
ENTITYCODELIST = 'entityCodeList'
ENTITYREFERENCE = 'entityReference'
EXTERNALCODESET = 'externalCodeSet'
EXTERNALLYDEFINEDFORMAT = 'externallyDefinedFormat'
EML = 'eml'
ENCODINGMETHOD = 'encodingMethod'
ENDDATE = 'endDate'
ENTITYDESCRIPTION = 'entityDescription'
ENTITYNAME = 'entityName'
ENUMERATEDDOMAIN = 'enumeratedDomain'
FIELDDELIMITER = 'fieldDelimiter'
FIELDSTARTCOLUMN = 'fieldStartColumn'
FIELDWIDTH = 'fieldWidth'
FORMATNAME = 'formatName'
FORMATVERSION = 'formatVersion'
GIVENNAME = 'givenName'
GENERALTAXONOMICCOVERAGE = 'generalTaxonomicCoverage'
GEOGRAPHICCOVERAGE = 'geographicCoverage'
GEOGRAPHICDESCRIPTION = 'geographicDescription'
INDIVIDUALNAME = 'individualName'
INLINE = 'inline'
INTERVAL = 'interval'
KEYWORD = 'keyword'
KEYWORDSET = 'keywordSet'
KEYWORDTHESAURUS = 'keywordThesaurus'
LAYOUT = 'layout'
LINENUMBER = 'lineNumber'
LITERALCHARACTER = 'literalCharacter'
MAXIMUM = 'maximum'
MAXRECORDLENGTH = 'maxRecordLength'
MEASUREMENTSCALE = 'measurementScale'
MEDIUMNAME = 'mediumName'
MEDIUMDENSITY = 'mediumDensity'
MEDIUMDENSITYUNITS = 'mediumDensityUnits'
MEDIUMVOLUME = 'mediumVolume'
MEDIUMFORMAT = 'mediumFormat'
MEDIUMNOTE = 'mediumNote'
METADATA = 'metadata'
METADATAPROVIDER = 'metadataProvider'
METHODS = 'methods'
METHODSTEP = 'methodStep'
MISSINGVALUECODE = 'missingValueCode'
MINIMUM = 'minimum'
MULTIBAND = 'multiBand'
NBANDS = 'nbands'
NBITS = 'nbits'
NOMINAL = 'nominal'
NONNUMERICDOMAIN = 'nonNumericDomain'
NORTHBOUNDINGCOORDINATE = 'northBoundingCoordinate'
NUMBEROFRECORDS = 'numberOfRecords'
NUMBERTYPE = 'numberType'
NUMERICDOMAIN = 'numericDomain'
NUMFOOTERLINES = 'numFooterLines'
NUMHEADERLINES = 'numHeaderLines'
NUMPHYSICALLINESPERRECORD = 'numPhysicalLinesPerRecord'
OBJECTNAME = 'objectName'
OFFLINE = 'offline'
ONLINE = 'online'
ONLINEDESCRIPTION = 'onlineDescription'
ONLINEURL = 'onlineUrl'
ORDERATTRIBUTEREFERENCE = 'orderAttributeReference'
ORDINAL = 'ordinal'
ORGANIZATIONNAME = 'organizationName'
PATTERN = 'pattern'
PERMISSION = 'permission'
PHONE = 'phone'
PHYSICAL = 'physical'
PHYSICALLINEDELIMITER = 'physicalLineDelimiter'
POSITIONNAME = 'positionName'
POSTALCODE = 'postalCode'
PRECISION = 'precision'
PRINCIPAL = 'principal'
PUBDATE = 'pubDate'
QUALITYCONTROL = 'qualityControl'
QUANTITATIVEATTRIBUTEACCURACYASSESSMENT = 'quantitativeAttributeAccuracyAssessment'
QUOTECHARACTER = 'quoteCharacter'
RANGEOFDATES = 'rangeOfDates'
RATIO = 'ratio'
ROWCOLUMNORIENTATION = 'rowColumnOrientation'
RECORDDELIMITER = 'recordDelimiter'
SALUTATION = 'salutation'
SAMPLING = 'sampling'
SIMPLEDELIMITED = 'simpleDelimited'
SINGLEDATETIME = 'singleDateTime'
SIZE = 'size'
SKIPBYTES = 'skipbytes'
SOURCE = 'source'
SOUTHBOUNDINGCOORDINATE = 'southBoundingCoordinate'
STANDARDUNIT = 'standardUnit'
STORAGETYPE = 'storageType'
SURNAME = 'surName'
TAXONOMICCLASSIFICATION = 'taxonomicClassification'
TAXONOMICCOVERAGE = 'taxonomicCoverage'
TAXONRANKNAME = 'taxonRankName'
TAXONRANKVALUE = 'taxonRankValue'
TEXTDELIMITED = 'textDelimited'
TEXTDOMAIN = 'textDomain'
TEXTFIXED = 'textFixed'
TEXTFORMAT = 'textFormat'
TEMPORALCOVERAGE = 'temporalCoverage'
TITLE = 'title'
TOTALROWBYTES = 'totalrowbytes'
UNIT = 'unit'
URL = 'url'
USERID = 'userId'
VALUE = 'value'
VALUEATTRIBUTEREFERENCE = 'valueAttributeReference'
WESTBOUNDINGCOORDINATE = 'westBoundingCoordinate'
